- name: Execute Spark jobs on remote hosts
  hosts: hosts
  become_user: root
  become: yes
  tasks:
    - name: Ensure /data/local/pipeline_scripts exists
      file:
        path: /data/local/pipeline_scripts
        state: directory

    - name: Execute test.py script on host
      command: >
        spark-submit test.py --csv_dir /data/local/extracted/stock-market-dataset/stocks
      args:
        chdir: /data/local/pipeline_scripts
      environment:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk
        SPARK_HOME: /opt/spark
        PATH: "{{ ansible_env.PATH }}:/usr/lib/jvm/java-11-openjdk/bin:/opt/spark/bin"