- name: Setup Cluster Nodes for COMP0235 Coursework
  hosts: storage
  become: true

  vars:
    shared_data_dir: /data/local/venv

  tasks:
    - name: Ensure shared data directory exists
      file:
        path: "{{ shared_data_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0777'

    - name: Ensure /data/tmp exists with appropriate permissions
      ansible.builtin.file:
        path: /data/tmp
        state: directory
        mode: '0777'
        owner: root
        group: root

    - name: Set /data/tmp as the temporary directory for Ansible
      ansible.builtin.lineinfile:
        path: /etc/ansible/ansible.cfg
        line: "remote_tmp = /data/tmp"
        insertafter: '[defaults]'
        create: yes

    - name: Download stock market dataset from Kaggle
      ansible.builtin.get_url:
        url: "https://www.kaggle.com/api/v1/datasets/download/jacksoncrow/stock-market-dataset"
        dest: "{{ shared_data_dir }}/stock-market-dataset.zip"
        mode: '0777'
        owner: root
        group: root
      vars:
        ansible_remote_tmp: /data/tmp

    - name: Ensure directory for extracted stock market dataset exists
      ansible.builtin.file:
        path: "{{ shared_data_dir }}/extracted/stock-market-dataset"
        state: directory
        mode: '0777'
        owner: root
        group: root

    - name: Unzip stock market dataset into extracted folder
      ansible.builtin.unarchive:
        src: "{{ shared_data_dir }}/stock-market-dataset.zip"
        dest: "{{ shared_data_dir }}/extracted/stock-market-dataset"
        remote_src: yes
        mode: '0777'
        owner: root
        group: root
