---
- name: Add SSH key for almalinux user
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Ensure SSH key is present in authorized_keys
      ansible.builtin.authorized_key:
        user: almalinux
        state: present
        key: "{{ lookup('file', '/home/almalinux/.ssh/id_rsa.pub') }}"
      ignore_errors: yes
    
    - name: Ensure lecture.pub key is present in authorized_keys
      ansible.builtin.authorized_key:
        user: almalinux
        state: present
        key: "{{ lookup('file', '/home/almalinux/CW2/terraform_combined/lecturer_key.pub') }}"
      ignore_errors: yes